language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env.testing
  - mysql -e 'create database tracy_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan passport:keys
  - curl -LO https://deployer.org/deployer.phar
  - chmod +x ./deployer.phar
services:
  - mysql

script:
  - vendor/bin/phpunit

deploy:
  provider: script
  script: deployer.phar deploy
  on:
    branch: develop

notifications:
  email: false
